version: "3"

services:
  web-server:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    volumes:
      - "../public/:/var/www/html/"
    ports:
      - "8081:80"

  db-server:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: server-mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "3333:80"

networks:
  sail:
    driver: bridge

volumes:
  mysql-data: